image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaDatEditor" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore XwaDatEditor\XwaDatEditor.sln

build:
  project: XwaDatEditor\XwaDatEditor.sln
  verbosity: minimal

after_build:
- XwaDatEditor\build-dist.cmd

artifacts:
- path: XwaDatEditor\dist
  name: XwaDatEditor-$(APPVEYOR_BUILD_VERSION)
  type: zip
